### ISSUE TITLE
Some README nits.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-python#17]
In the README it says "
There is initial support for many of Egeria's services including configuraiton, operation, and use. This client depends on Egeria 4.4 Snapshot and above - although most of the functions may work on earlier versions of Egeria as well."

some nits:

- `configuraiton` spelling
- `and use`. I am not sure what this means. Maybe mention the other omvs capabilities you current support explicitly.
- the client can only depend on one version of Egeria- it can support higher versions - I think. So I suggest rephrasing "`Egeria 4.4 Snapshot and above`". If this is not a strict dependancy on the JAVA code, maybe say `will work with Egeria 4.4 Snapshot and above`.

**Comment by dwolfson** [comment]
Thank you - updates to the README have been made.
